title: Yeh Yu-Ting
logo: /pf_photos/logo_circled.png
description: Hi! I'm Yu-Ting, an enthusiastic about data. I'm a lazy person, so I would like to save my time by finding efficient solutions toward complex problems by numbers, coding and my wisdom!
show_download: True
theme: jekyll-theme-minimal
