title: Andy Yeh
logo: circle.png
description: Hi! I'm Andy. Welcome to my portfolio! I am a Statistics graduate student at Rice University . I am familiar with SQL, Python, R and focus on data analysis, ML, and LLM applications. Feel free to reach out to me. yy152@rice.edu 
theme: jekyll-theme-minimal
